name: bytestash
services:
  bytestash:
    image: ghcr.io/jordan-dalby/bytestash:latest
    container_name: bytestash
    restart: unless-stopped
    volumes:
    - /opt/bytestash/snippets:/data/snippets
    environment:
      BASE_PATH: ''
      JWT_SECRET: ${JWT_SECRET}
      TOKEN_EXPIRY: 24h
      ALLOW_NEW_ACCOUNTS: 'true'
      DEBUG: 'true'
      DISABLE_ACCOUNTS: 'false'
      DISABLE_INTERNAL_ACCOUNTS: 'false'
      OIDC_ENABLED: 'false'
      OIDC_DISPLAY_NAME: ''
      OIDC_ISSUER_URL: ''
      OIDC_CLIENT_ID: ''
      OIDC_CLIENT_SECRET: ''
      OIDC_SCOPES: ''
    expose:
    - '5000'
    networks:
    - proxy
    env_file:
    - .env
networks:
  proxy:
    external: true
    name: proxy
