name: termix
services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    restart: unless-stopped
    volumes:
    - /opt/termix/app:/app/data
    environment:
      PORT: '8050'
    expose:
    - '8050'
    networks:
    - proxy
networks:
  proxy:
    external: true
    name: proxy
