name: planka
services:
  planka:
    image: ghcr.io/plankanban/planka:2.0.0-rc.3
    restart: unless-stopped
    volumes:
    - /opt/planka/favicons:/app/public/favicons
    - /opt/planka/avatars:/app/public/user-avatars
    - /opt/planka/backgrounds:/app/public/background-images
    - /opt/planka/attachments:/app/private/attachments
    environment:
    - BASE_URL=http://localhost:1337
    - DATABASE_URL=postgresql://postgres@postgres/planka
    - SECRET_KEY=27337bdca9020ca2488869df10daa4dd12fe3
    depends_on:
      postgres:
        condition: service_healthy
    container_name: planka-app
    expose:
    - '1337'
    networks:
    - proxy
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
    - /opt/planka/db:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=planka
    - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres -d planka
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: planka-postgres
    networks:
    - proxy
    expose:
    - '5432'
networks:
  proxy:
    external: true
    name: proxy
