services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1001:1001 # should be owner of volumes
    ports:
      - "127.0.0.1:4533:4533"
    restart: unless-stopped
    # environment:
      # Optional: put your config options customization here. Examples:
      # ND_LOGLEVEL: debug
    volumes:
      - "/opt/navidrome/data:/data"
      - "/mnt/volume_sgp1_01/music:/music:ro"

