services:
  beszel:
    image: henrygd/beszel:0.16.0
    container_name: beszel
    restart: unless-stopped
    # ports:
    #   - 8090:8090
    volumes:
      - /opt/beszel/data:/beszel_data
      - /opt/beszel/socket:/beszel_socket
    networks:
      - caddy_net
    environment:
      DISABLE_PASSWORD_AUTH: true
      USER_CREATION: true
      APP_URL: https://stats.abdulkareem.codes

  beszel-agent:
    image: henrygd/beszel-agent:0.16.0-alpine
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/beszel/agent/data:/var/lib/beszel-agent
      - /opt/beszel/socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: https://stats.abdulkareem.codes
      TOKEN: acad2922-6d93-41c2-b319-a8acae7ac638
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAIn+c054shAAuOJ3oH2wk4QFxEucTACjTHf/FlAJhhJ"

networks:
  caddy_net:
    external: true
