services:
  convertx:
    image: ghcr.io/c4illin/convertx:v0.15.1
    container_name: convertx
    restart: unless-stopped
    environment:
      - HTTP_ALLOWED=false
      - ALLOW_UNAUTHENTICATED=true
      - ACCOUNT_REGISTRATION=false
      - HIDE_HISTORY=true
    env_file: 
      - .env
    volumes:
      - /opt/convertx/data:/app/data
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
