name: silverbullet
services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet:v2
    restart: unless-stopped
    environment:
    - SB_USER=admin:admin
    volumes:
    - /opt/silverbullet/space:/space
    container_name: silverbullet
    expose:
    - '3000'
    networks:
    - proxy
networks:
  proxy:
    external: true
    name: proxy
