name: Deploy Memos

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "memos/**"


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Copy files to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          source: "memos"
          target: "/home/deploy/services/"
          rm: false

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /home/deploy/services/memos

            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
