name: Deploy Caddy

on: 
  push:
    branches:
      - main
    paths:
      - "caddy/**"


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Inject .env file
        run: |
          echo "${{ secrets.ENV_CADDY }}" > caddy/.env

      - name: Copy files to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          source: "caddy"
          target: "/home/deploy/services/"
          rm: false

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /home/deploy/services/caddy

            if [ $(docker ps -q -f name=caddy) ]; then
              echo "Caddy is running. Starting Zero-Downtime Update..."

              docker compose exec -w /etc/caddy caddy caddy fmt --overwrite

              if docker compose exec -w /etc/caddy caddy caddy validate; then
                echo "Validation successful. Reloading..."

                docker compose exec -w /etc/caddy caddy caddy reload
              else
                 echo "CRITICAL: Caddyfile validation failed! Not reloading."
                 exit 1
              fi

            else
              echo "Caddy is not running. Starting fresh..."
              docker compose pull
              docker compose up -d --remove-orphans
              docker image prune -f
            fi
